name: cherry-picker-on-close

on:
  pull_request_target:
    types: [closed]

env:
  GH_TOKEN: ${{ secrets.SECRET_TOKEN }}

jobs:
  cherry-picker-on-close:
    # if: github.event.pull_request.user.login == 'copybara'
    runs-on: ubuntu-latest
    steps:
      - name: Logging github event
        run: echo '${{ toJSON(github.event) }}' | jq
      - name: Run cherrypicker on close
        run: echo "Test"
